### ISSUE TITLE
Duplication in custom made minefield

### ISSUE THREAD

**Issue by kyana1234** [LWprogramming/Minefinder#27]
![image](https://user-images.githubusercontent.com/25754735/29000835-525456d6-7a2d-11e7-8036-991e6d2a990f.png)
I made a custom 2x2 field with 1 mine. I am using Google Chrome and it displayed 2 rows and 4 columns. I think it displays duplicated columns because I died by 2 mines. I attempted to upload a picture of the issue

**Comment by kyana1234** [comment]
![image](https://user-images.githubusercontent.com/25754735/29000841-9b2c9490-7a2d-11e7-86a2-acca2a3f44ca.png)
I tried again with a different custom dimension. I attempted to make a 3x3 but it displays a 3 x 6 with double amount of mines.

**Comment by LWprogramming** [comment]
Thanks for catching this bug! I experimented further and it appears that the bug occurs when the number 12 is a multiple of the number of columns. This should have something to do with this line of code in index.js:

`button.className = 'button col-xs-' + 12 / numCols;`

I used to represent the state of each square using text, so this used to be relevant. Now that we're doing that with images instead and setting the size of the button to the size of the image, removing this should fix the problem.

**Comment by LWprogramming** [comment]
![screenshot from 2017-08-07 09 58 32](https://user-images.githubusercontent.com/13173037/29029891-34eee27a-7b57-11e7-9782-bf1f383c3c9d.png)
![screenshot from 2017-08-07 09 59 33](https://user-images.githubusercontent.com/13173037/29029892-34ef0e8a-7b57-11e7-999e-eb0d2040226b.png)
![screenshot from 2017-08-07 09 59 51](https://user-images.githubusercontent.com/13173037/29029893-34f134e4-7b57-11e7-8598-362ee5620b02.png)
